---
# Main task file - HA deployment only

- name: Set up workload for user
  when:
    - not ocp4_workload_litemaas_remove | bool
  block:
    - name: Run pre_workload tasks
      ansible.builtin.include_tasks: pre_workload.yml

    - name: Run HA workload tasks
      ansible.builtin.include_tasks: workload_litemaas_ha.yml

- name: Remove workload
  when: ocp4_workload_litemaas_remove | bool
  block:
    - name: Run remove_workload tasks
      ansible.builtin.include_tasks: remove_workload.yml
